### ISSUE TITLE
[Query] Clarification on specs

### ISSUE THREAD

**Issue by brootware** [cdr/docs#531]
https://github.com/cdr/docs/blob/022e07279f87e03b3edcca1fe1ac1e4483d65509/setup/requirements.md

Hi folks, just a clarification on the recommended infrastructure requirements. Here it is stated that

For Development using VS Code with an SSH connection to Coder: 1 CPU core and 1 GB of RAM per developer. From the context it seems like it's a virtual machine specification. Can this be translated to a pod resource that needs to be defined as below in pod definition?

```
resources:
  requests:
    cpu: "1000m"
    memory: "1Gi"
```
